---
- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

- name: Provision OSP servers
  hosts: workstation
  roles:
  - osp-servers
