---
# Playbook to setup workstation and create osp network, router, SG and ssh keypair

- name: create the workstation group
  hosts: localhost
  become: yes
  roles:
  - create-workstation

- name: setup the workstation environment
  hosts: workstation
  become: yes
  roles:
  - setup-workstation

- name: import the site-install-isolated-node playbook
  import_playbook: site-install-isolated-node.yml 
