- name: create the workstation group
  hosts: localhost
  roles:
  - create-workstation

- hosts: workstation
  gather_facts: true
  become: yes
  roles:
  - name: osp-facts

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

#- name: import aws smoke test
#  import_playbook: site-smoketest-aws.yml

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
