---
# vars file for osp.servers
ospem_path: "/root/.ssh/openstack.pem"
ospub_path: "root/.ssh/openstack.pub"
mykey_path: "root/.ssh/mykey.pem"


osp_image: rhel-guest
ansible_key: ansible_ssh
osp_flavor: m2.small
public_network: ext_network
yum_repo: http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo

osp_servers:
  frontend:
    name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: frontend
    network: ext_network
    meta: 
     group: frontends
     deployment_name: QA
  app1:
    name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    network: ext_network
    meta: 
      group: frontends
      deployment_name: QA
  app2:
    name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    network: ext_network
    meta: 
      group: frontends
      deployment_name: QA
  db:
    name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: db
    network: ext_network
    meta: 
      group: frontends
      deployment_name: QA
