---
# vars file for osp.servers
ospem_path: ~/.ssh/openstack.pem
ospub_path: ~/.ssh/openstack.pub
mykey_path: ~/.ssh/mykey.pem


osp_image: rhel-guest
ansible_key: ansible_ssh
osp_flavor: m2.small
public_network: ext_network

yum_repos:
  rhel-7-server-rpms:
    description: Main RHEL 7 packages
    baseurl: http://admin.na.shared.opentlc.com/repos/ocp/3.6//rhel-7-server-rpms
    enabled: yes
    gpgcheck: no
  rhel-7-server-rh-common-rpms:
    description: RHEL 7 Common packages
    baseurl: http://admin.na.shared.opentlc.com/repos/ocp/3.6//rhel-7-server-rh-common-rpms
    enabled: yes
    gpgcheck: no
  rhel-7-server-extras-rpms:
    description: RHEL 7 Extra packages
    baseurl: hhttp://admin.na.shared.opentlc.com/repos/ocp/3.6//rhel-7-server-extras-rpms
    enabled: yes
    gpgcheck: no
  rhel-7-server-optional-rpms:
    description: RHEL 7 Optional packages
    baseurl: http://admin.na.shared.opentlc.com/repos/ocp/3.6//rhel-7-server-optional-rpms
    enabled: yes
    gpgcheck: no
  epel:
    description: EPEL repo
    baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
    enabled: yes
    gpgcheck: no
    failovermethod: priority

osp_servers:
  frontend:
    name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: frontend
    network: ext_network
    meta: 
     group: frontends
     deployment_name: QA
  app1:
    name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    network: ext_network
    meta: 
      group: frontends
      deployment_name: QA
  app2:
    name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    network: ext_network
    meta: 
      group: frontends
      deployment_name: QA
  db:
    name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: db
    network: ext_networ
    meta: 
      group: frontends
      deployment_name: QA
