---
# tasks file for osp.servers

- name: Create frontend server instances and attach them to a network and pass metadata to the instance
  os_server:
    auth: 
      auth_url: 192.168.0.20:5000/
      project_name: admin
      username: admin
      password: "{{ osp_password }}"
    identity_api_version: "3.0"
    region_name: RegionOne
    name: frontend
    state: present
    image: "{{ osp_image }}"
    key_name: "{{ ansible_key }}"
    flavor: "{{ osp_flavor }}"
    security_group: frontend
    network: "{{ public_network }}"
#    floating_ips:
#      - 1.1.1.1
    meta:
      - { group: frontends, deployment_name: QA}

#- name: Create frontend server instances and attach them to a network and pass metadata to the instance
#    os_server:
#      name: app1
#      state: present
#      image: "{{ osp_image }}"
#      key_name: "{{ ansible_key }}"
#      flavor: "{{ osp_flavor }}"
#      security_group: apps
#      meta:
#        - { group: apps, deployment_name: QA}
#    app2:
#      name: app2
#      state: present
#      image: "{{ osp_image }}"
#      key_name: "{{ ansible_key }}"
#      flavor: "{{ osp_flavor }}"
#      security_group: apps
#      meta:
#        - { group: apps, deployment_name: QA}
#    db:
#      name: db
#      state: present
#      image: "{{ osp_image }}"
#      key_name: "{{ ansible_key }}"
#      flavor: "{{ osp_flavor }}"
#      security_group: db
#      meta:
#        - { group: appdbs, deployment_name: QA}


#- name: Add floating IP to Servers
   

#- name: Wait for server to be available
#  wait_for:
#    port: 22
