---
# tasks file for osp.servers

- name: Create frontend server instances and attach them to a network and pass metadata to the instance
  os_server:
    name: "{{ item.key }}"
    state: "{{ item.value.state }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    flavor: "{{ item.value.flavor }}"
    security_groups: "{{ item.value.security_group }}"
    network: "{{ item.value.network }}"
    meta: "{{ item.value.meta }}"
  with_dict: "{{ osp_servers }}"

- name: Use the organization's local yum repo
  yum_repository:
    name: "{{ item.key }}"
    baseurl: "{{ item.value.baseurl }}"
    enabled: "{{ item.value.enabled }}"
    gpgcheck: "{{ item.value.gpgcheck }}"
  with_dict: "{{ yum_repo }}"
#  loop: "{{ x }}"

- name: Add floating IP to Servers
  os_floating_ip:
    server: frontend
     
- name: Wait for server to be available
  wait_for:
    port: 22
