---
- name: create workstation group
  add_host:
    name: "workstation-987e.rhpds.opentlc.com"
    group: workstation
#    ansible_ssh_private_key_file: ~/.ssh/openstack.pem
#    ansible_ssh_user: cloud-user
